[[articles]]
filename = "on-definition.md"
name = "「定義」は共通でなくていい、あるいはこのブログの「定義」"
uri = "http://koba-e964-zatsu.hatenablog.com/entry/2025/11/10/185608"

[[articles]]
filename = "common-sense/article.md"
name = "「常識」は「知るのが簡単」という意味ではない、あるいは「知らないとヤバい」を拾う方法"
uri = "https://koba-e964-zatsu.hatenablog.com/entry/2025/11/30/235552"

[[articles]]
filename = "stopped-watching-shogi.md"
name = "将棋中継を観るのをやめた"
uri = "https://koba-e964-zatsu.hatenablog.com/entry/2025/12/11/201300"

[[articles]]
filename = "irritation.md"
name = "思い通りにならないことにイライラしてしまう"
uri = "https://koba-e964-zatsu.hatenablog.com/entry/2025/12/18/205344"
tags = ["イライラ　抑える方法"]

[[articles]]
filename = "dont-want-to-load-context.md"
name = "「頭に入れたくない」との戦い"
uri = "https://koba-e964-zatsu.hatenablog.com/entry/2025/12/27/203507"
tags = ["先延ばししない技術"]
